// GENERATED by scripts/gen-catalog-seed.mjs — do not edit by hand.
// Storefront fallback data (used only when the catalog service is unreachable).
import type { MockCategory, MockProduct } from "./mock-data";

export const MOCK_CATEGORIES: MockCategory[] = [
  {
    "id": "1",
    "slug": "case",
    "name": "Cases",
    "description": "ATX, mATX, and ITX enclosures",
    "productCount": 23,
    "icon": "□"
  },
  {
    "id": "2",
    "slug": "controller",
    "name": "Controllers",
    "description": "Gamepads for PC and console",
    "productCount": 30,
    "icon": "✦"
  },
  {
    "id": "3",
    "slug": "cooler",
    "name": "Coolers",
    "description": "Air and liquid CPU cooling",
    "productCount": 26,
    "icon": "◌"
  },
  {
    "id": "4",
    "slug": "cpu",
    "name": "CPUs",
    "description": "Processors from AMD and Intel",
    "productCount": 22,
    "icon": "◈"
  },
  {
    "id": "5",
    "slug": "gpu",
    "name": "GPUs",
    "description": "Graphics cards for gaming and creation",
    "productCount": 29,
    "icon": "▣"
  },
  {
    "id": "6",
    "slug": "headset",
    "name": "Headsets",
    "description": "Gaming headsets and audio",
    "productCount": 25,
    "icon": "◯"
  },
  {
    "id": "7",
    "slug": "keyboard",
    "name": "Keyboards",
    "description": "Mechanical and low-profile keyboards",
    "productCount": 21,
    "icon": "▦"
  },
  {
    "id": "8",
    "slug": "laptop",
    "name": "Laptops",
    "description": "Gaming and creator laptops",
    "productCount": 28,
    "icon": "▭"
  },
  {
    "id": "9",
    "slug": "memory",
    "name": "Memory",
    "description": "DDR5 and DDR4 RAM kits",
    "productCount": 24,
    "icon": "▤"
  },
  {
    "id": "10",
    "slug": "monitor",
    "name": "Monitors",
    "description": "High-refresh gaming displays",
    "productCount": 20,
    "icon": "▥"
  },
  {
    "id": "11",
    "slug": "motherboard",
    "name": "Motherboards",
    "description": "Boards for every platform",
    "productCount": 27,
    "icon": "⊞"
  },
  {
    "id": "12",
    "slug": "mouse",
    "name": "Mice",
    "description": "Gaming mice and sensors",
    "productCount": 23,
    "icon": "◑"
  },
  {
    "id": "13",
    "slug": "powersupply",
    "name": "Power Supplies",
    "description": "Efficient, quiet PSUs",
    "productCount": 30,
    "icon": "◧"
  },
  {
    "id": "14",
    "slug": "storage",
    "name": "Storage",
    "description": "NVMe SSDs and drives",
    "productCount": 26,
    "icon": "◫"
  }
];

export const MOCK_PRODUCTS: MockProduct[] = [
  {
    "id": "1",
    "sku": "CASE-0000",
    "slug": "nzxt-h7-flow-case-1",
    "name": "NZXT H7 Flow A100",
    "brand": "NZXT",
    "description": "NZXT H7 Flow A100 — atx, matx, and itx enclosures.",
    "categorySlug": "case",
    "priceCents": 7520,
    "stockStatus": "out-of-stock",
    "specs": {
      "Form Factor": "ATX",
      "Side Panel": "Tempered Glass",
      "Fans Included": "2",
      "Max GPU Length": "330 mm"
    },
    "imageUrl": "http://localhost:8080/images/case1.webp"
  },
  {
    "id": "2",
    "sku": "CASE-0001",
    "slug": "corsair-5000d-case-2",
    "name": "Corsair 5000D B101",
    "brand": "Corsair",
    "description": "Corsair 5000D B101 — atx, matx, and itx enclosures.",
    "categorySlug": "case",
    "priceCents": 8041,
    "stockStatus": "in-stock",
    "specs": {
      "Form Factor": "mATX",
      "Side Panel": "Tempered Glass",
      "Fans Included": "3",
      "Max GPU Length": "340 mm"
    },
    "imageUrl": "http://localhost:8080/images/case2.webp"
  },
  {
    "id": "3",
    "sku": "CASE-0002",
    "slug": "lian-li-o11-dynamic-case-3",
    "name": "Lian Li O11 Dynamic C102",
    "brand": "Lian Li",
    "description": "Lian Li O11 Dynamic C102 — atx, matx, and itx enclosures.",
    "categorySlug": "case",
    "priceCents": 8562,
    "stockStatus": "in-stock",
    "specs": {
      "Form Factor": "ITX",
      "Side Panel": "Tempered Glass",
      "Fans Included": "4",
      "Max GPU Length": "350 mm"
    },
    "imageUrl": "http://localhost:8080/images/case3.webp"
  },
  {
    "id": "4",
    "sku": "CASE-0003",
    "slug": "fractal-design-meshify-case-4",
    "name": "Fractal Design Meshify D103",
    "brand": "Fractal Design",
    "description": "Fractal Design Meshify D103 — atx, matx, and itx enclosures.",
    "categorySlug": "case",
    "priceCents": 9083,
    "stockStatus": "in-stock",
    "specs": {
      "Form Factor": "ATX",
      "Side Panel": "Tempered Glass",
      "Fans Included": "5",
      "Max GPU Length": "360 mm"
    },
    "imageUrl": "http://localhost:8080/images/case4.webp"
  },
  {
    "id": "5",
    "sku": "CTRL-0100",
    "slug": "xbox-elite-series-2-controller-1",
    "name": "Xbox Elite Series 2 A100",
    "brand": "Xbox",
    "description": "Xbox Elite Series 2 A100 — gamepads for pc and console.",
    "categorySlug": "controller",
    "priceCents": 5520,
    "stockStatus": "in-stock",
    "specs": {
      "Connectivity": "2.4 GHz Wireless",
      "Battery Life": "15 h",
      "Hall-Effect Sticks": "No"
    },
    "imageUrl": "http://localhost:8080/images/controller1.webp"
  },
  {
    "id": "6",
    "sku": "CTRL-0101",
    "slug": "sony-dualsense-edge-controller-2",
    "name": "Sony DualSense Edge B101",
    "brand": "Sony",
    "description": "Sony DualSense Edge B101 — gamepads for pc and console.",
    "categorySlug": "controller",
    "priceCents": 6041,
    "stockStatus": "in-stock",
    "specs": {
      "Connectivity": "Bluetooth + USB-C",
      "Battery Life": "16 h",
      "Hall-Effect Sticks": "Yes"
    },
    "imageUrl": "http://localhost:8080/images/controller1.webp"
  },
  {
    "id": "7",
    "sku": "CTRL-0102",
    "slug": "8bitdo-ultimate-controller-3",
    "name": "8BitDo Ultimate C102",
    "brand": "8BitDo",
    "description": "8BitDo Ultimate C102 — gamepads for pc and console.",
    "categorySlug": "controller",
    "priceCents": 6562,
    "stockStatus": "in-stock",
    "specs": {
      "Connectivity": "2.4 GHz Wireless",
      "Battery Life": "17 h",
      "Hall-Effect Sticks": "No"
    },
    "imageUrl": "http://localhost:8080/images/controller1.webp"
  },
  {
    "id": "8",
    "sku": "CTRL-0103",
    "slug": "razer-wolverine-v2-controller-4",
    "name": "Razer Wolverine V2 D103",
    "brand": "Razer",
    "description": "Razer Wolverine V2 D103 — gamepads for pc and console.",
    "categorySlug": "controller",
    "priceCents": 7083,
    "stockStatus": "in-stock",
    "specs": {
      "Connectivity": "Bluetooth + USB-C",
      "Battery Life": "18 h",
      "Hall-Effect Sticks": "Yes"
    },
    "imageUrl": "http://localhost:8080/images/controller1.webp"
  },
  {
    "id": "9",
    "sku": "COOL-0200",
    "slug": "noctua-nh-d15-cooler-1",
    "name": "Noctua NH-D15 A100",
    "brand": "Noctua",
    "description": "Noctua NH-D15 A100 — air and liquid cpu cooling.",
    "categorySlug": "cooler",
    "priceCents": 4520,
    "stockStatus": "in-stock",
    "specs": {
      "Type": "Dual-Tower Air",
      "TDP": "180 W",
      "Fan Speed": "1500 RPM",
      "Socket": "LGA1700"
    },
    "imageUrl": "http://localhost:8080/images/case1.webp"
  },
  {
    "id": "10",
    "sku": "COOL-0201",
    "slug": "corsair-icue-h150i-cooler-2",
    "name": "Corsair iCUE H150i B101",
    "brand": "Corsair",
    "description": "Corsair iCUE H150i B101 — air and liquid cpu cooling.",
    "categorySlug": "cooler",
    "priceCents": 5041,
    "stockStatus": "in-stock",
    "specs": {
      "Type": "360 mm AIO",
      "TDP": "200 W",
      "Fan Speed": "1600 RPM",
      "Socket": "AM5 / LGA1700"
    },
    "imageUrl": "http://localhost:8080/images/case2.webp"
  },
  {
    "id": "11",
    "sku": "COOL-0202",
    "slug": "be-quiet-dark-rock-pro-cooler-3",
    "name": "be quiet! Dark Rock Pro C102",
    "brand": "be quiet!",
    "description": "be quiet! Dark Rock Pro C102 — air and liquid cpu cooling.",
    "categorySlug": "cooler",
    "priceCents": 5562,
    "stockStatus": "in-stock",
    "specs": {
      "Type": "Dual-Tower Air",
      "TDP": "220 W",
      "Fan Speed": "1700 RPM",
      "Socket": "LGA1700"
    },
    "imageUrl": "http://localhost:8080/images/case3.webp"
  },
  {
    "id": "12",
    "sku": "COOL-0203",
    "slug": "arctic-liquid-freezer-iii-cooler-4",
    "name": "Arctic Liquid Freezer III D103",
    "brand": "Arctic",
    "description": "Arctic Liquid Freezer III D103 — air and liquid cpu cooling.",
    "categorySlug": "cooler",
    "priceCents": 6083,
    "stockStatus": "in-stock",
    "specs": {
      "Type": "360 mm AIO",
      "TDP": "240 W",
      "Fan Speed": "1800 RPM",
      "Socket": "AM5 / LGA1700"
    },
    "imageUrl": "http://localhost:8080/images/case4.webp"
  },
  {
    "id": "13",
    "sku": "CPU-0300",
    "slug": "intel-core-i9-cpu-1",
    "name": "Intel Core i9 A100",
    "brand": "Intel",
    "description": "Intel Core i9 A100 — processors from amd and intel.",
    "categorySlug": "cpu",
    "priceCents": 19520,
    "stockStatus": "in-stock",
    "specs": {
      "Cores": "6",
      "Boost Clock": "5.0 GHz",
      "TDP": "65 W",
      "Socket": "LGA1700"
    },
    "imageUrl": "http://localhost:8080/images/cpu1.jpg"
  },
  {
    "id": "14",
    "sku": "CPU-0301",
    "slug": "amd-core-i7-cpu-2",
    "name": "AMD Core i7 B101",
    "brand": "AMD",
    "description": "AMD Core i7 B101 — processors from amd and intel.",
    "categorySlug": "cpu",
    "priceCents": 20041,
    "stockStatus": "in-stock",
    "specs": {
      "Cores": "8",
      "Boost Clock": "5.1 GHz",
      "TDP": "100 W",
      "Socket": "AM5"
    },
    "imageUrl": "http://localhost:8080/images/cpu2.png"
  },
  {
    "id": "15",
    "sku": "CPU-0302",
    "slug": "intel-core-i5-cpu-3",
    "name": "Intel Core i5 C102",
    "brand": "Intel",
    "description": "Intel Core i5 C102 — processors from amd and intel.",
    "categorySlug": "cpu",
    "priceCents": 20562,
    "stockStatus": "in-stock",
    "specs": {
      "Cores": "10",
      "Boost Clock": "5.2 GHz",
      "TDP": "135 W",
      "Socket": "LGA1700"
    },
    "imageUrl": "http://localhost:8080/images/cpu3.jpg"
  },
  {
    "id": "16",
    "sku": "CPU-0303",
    "slug": "amd-ryzen-9-cpu-4",
    "name": "AMD Ryzen 9 D103",
    "brand": "AMD",
    "description": "AMD Ryzen 9 D103 — processors from amd and intel.",
    "categorySlug": "cpu",
    "priceCents": 21083,
    "stockStatus": "in-stock",
    "specs": {
      "Cores": "12",
      "Boost Clock": "5.3 GHz",
      "TDP": "170 W",
      "Socket": "AM5"
    },
    "imageUrl": "http://localhost:8080/images/cpu4.webp"
  },
  {
    "id": "17",
    "sku": "GPU-0400",
    "slug": "asus-rog-rtx-4090-gpu-1",
    "name": "ASUS ROG RTX 4090 A100",
    "brand": "ASUS ROG",
    "description": "ASUS ROG RTX 4090 A100 — graphics cards for gaming and creation.",
    "categorySlug": "gpu",
    "priceCents": 50520,
    "stockStatus": "in-stock",
    "specs": {
      "VRAM": "12 GB GDDR6X",
      "TDP": "250 W",
      "Boost Clock": "2.30 GHz",
      "Outputs": "3× DP, 1× HDMI"
    },
    "imageUrl": "http://localhost:8080/images/gpu1.webp"
  },
  {
    "id": "18",
    "sku": "GPU-0401",
    "slug": "msi-rtx-4080-super-gpu-2",
    "name": "MSI RTX 4080 Super B101",
    "brand": "MSI",
    "description": "MSI RTX 4080 Super B101 — graphics cards for gaming and creation.",
    "categorySlug": "gpu",
    "priceCents": 51041,
    "stockStatus": "in-stock",
    "specs": {
      "VRAM": "16 GB GDDR6X",
      "TDP": "280 W",
      "Boost Clock": "2.35 GHz",
      "Outputs": "3× DP, 1× HDMI"
    },
    "imageUrl": "http://localhost:8080/images/gpu2.webp"
  },
  {
    "id": "19",
    "sku": "GPU-0402",
    "slug": "gigabyte-rtx-4070-ti-gpu-3",
    "name": "Gigabyte RTX 4070 Ti C102",
    "brand": "Gigabyte",
    "description": "Gigabyte RTX 4070 Ti C102 — graphics cards for gaming and creation.",
    "categorySlug": "gpu",
    "priceCents": 51562,
    "stockStatus": "in-stock",
    "specs": {
      "VRAM": "20 GB GDDR6X",
      "TDP": "310 W",
      "Boost Clock": "2.40 GHz",
      "Outputs": "3× DP, 1× HDMI"
    },
    "imageUrl": "http://localhost:8080/images/gpu3.webp"
  },
  {
    "id": "20",
    "sku": "GPU-0403",
    "slug": "nvidia-rx-7900-xtx-gpu-4",
    "name": "NVIDIA RX 7900 XTX D103",
    "brand": "NVIDIA",
    "description": "NVIDIA RX 7900 XTX D103 — graphics cards for gaming and creation.",
    "categorySlug": "gpu",
    "priceCents": 52083,
    "stockStatus": "low-stock",
    "specs": {
      "VRAM": "24 GB GDDR6X",
      "TDP": "340 W",
      "Boost Clock": "2.45 GHz",
      "Outputs": "3× DP, 1× HDMI"
    },
    "imageUrl": "http://localhost:8080/images/gpu4.webp"
  },
  {
    "id": "21",
    "sku": "HEAD-0500",
    "slug": "steelseries-arctis-nova-pro-headset-1",
    "name": "SteelSeries Arctis Nova Pro A100",
    "brand": "SteelSeries",
    "description": "SteelSeries Arctis Nova Pro A100 — gaming headsets and audio.",
    "categorySlug": "headset",
    "priceCents": 5520,
    "stockStatus": "in-stock",
    "specs": {
      "Driver": "40 mm",
      "Connectivity": "USB + 3.5 mm",
      "Microphone": "Detachable",
      "Surround": "Spatial Audio"
    },
    "imageUrl": "http://localhost:8080/images/headset1.webp"
  },
  {
    "id": "22",
    "sku": "HEAD-0501",
    "slug": "logitech-g-astro-a50-headset-2",
    "name": "Logitech G Astro A50 B101",
    "brand": "Logitech G",
    "description": "Logitech G Astro A50 B101 — gaming headsets and audio.",
    "categorySlug": "headset",
    "priceCents": 6041,
    "stockStatus": "in-stock",
    "specs": {
      "Driver": "50 mm",
      "Connectivity": "Wireless 2.4 GHz",
      "Microphone": "Detachable",
      "Surround": "Spatial Audio"
    },
    "imageUrl": "http://localhost:8080/images/headset2.webp"
  },
  {
    "id": "23",
    "sku": "HEAD-0502",
    "slug": "hyperx-cloud-iii-headset-3",
    "name": "HyperX Cloud III C102",
    "brand": "HyperX",
    "description": "HyperX Cloud III C102 — gaming headsets and audio.",
    "categorySlug": "headset",
    "priceCents": 6562,
    "stockStatus": "low-stock",
    "specs": {
      "Driver": "60 mm",
      "Connectivity": "USB + 3.5 mm",
      "Microphone": "Detachable",
      "Surround": "Spatial Audio"
    },
    "imageUrl": "http://localhost:8080/images/headset3.webp"
  },
  {
    "id": "24",
    "sku": "HEAD-0503",
    "slug": "razer-blackshark-v2-headset-4",
    "name": "Razer BlackShark V2 D103",
    "brand": "Razer",
    "description": "Razer BlackShark V2 D103 — gaming headsets and audio.",
    "categorySlug": "headset",
    "priceCents": 7083,
    "stockStatus": "in-stock",
    "specs": {
      "Driver": "40 mm",
      "Connectivity": "Wireless 2.4 GHz",
      "Microphone": "Detachable",
      "Surround": "Spatial Audio"
    },
    "imageUrl": "http://localhost:8080/images/headset4.webp"
  },
  {
    "id": "25",
    "sku": "KEYB-0600",
    "slug": "corsair-k100-rgb-keyboard-1",
    "name": "Corsair K100 RGB A100",
    "brand": "Corsair",
    "description": "Corsair K100 RGB A100 — mechanical and low-profile keyboards.",
    "categorySlug": "keyboard",
    "priceCents": 8520,
    "stockStatus": "in-stock",
    "specs": {
      "Switch": "Cherry MX Red",
      "Layout": "Full (100%)",
      "Backlight": "Per-key RGB",
      "Connectivity": "Wireless + USB-C"
    },
    "imageUrl": "http://localhost:8080/images/keyboard1.webp"
  },
  {
    "id": "26",
    "sku": "KEYB-0601",
    "slug": "razer-huntsman-v3-keyboard-2",
    "name": "Razer Huntsman V3 B101",
    "brand": "Razer",
    "description": "Razer Huntsman V3 B101 — mechanical and low-profile keyboards.",
    "categorySlug": "keyboard",
    "priceCents": 9041,
    "stockStatus": "low-stock",
    "specs": {
      "Switch": "Optical",
      "Layout": "TKL (80%)",
      "Backlight": "Per-key RGB",
      "Connectivity": "USB-C"
    },
    "imageUrl": "http://localhost:8080/images/keyboard2.webp"
  },
  {
    "id": "27",
    "sku": "KEYB-0602",
    "slug": "keychron-q1-pro-keyboard-3",
    "name": "Keychron Q1 Pro C102",
    "brand": "Keychron",
    "description": "Keychron Q1 Pro C102 — mechanical and low-profile keyboards.",
    "categorySlug": "keyboard",
    "priceCents": 9562,
    "stockStatus": "in-stock",
    "specs": {
      "Switch": "Hall-Effect",
      "Layout": "75%",
      "Backlight": "Per-key RGB",
      "Connectivity": "Wireless + USB-C"
    },
    "imageUrl": "http://localhost:8080/images/keyboard3.webp"
  },
  {
    "id": "28",
    "sku": "KEYB-0603",
    "slug": "logitech-g-g915-keyboard-4",
    "name": "Logitech G G915 D103",
    "brand": "Logitech G",
    "description": "Logitech G G915 D103 — mechanical and low-profile keyboards.",
    "categorySlug": "keyboard",
    "priceCents": 10083,
    "stockStatus": "in-stock",
    "specs": {
      "Switch": "Tactile Brown",
      "Layout": "65%",
      "Backlight": "Per-key RGB",
      "Connectivity": "USB-C"
    },
    "imageUrl": "http://localhost:8080/images/keyboard4.webp"
  },
  {
    "id": "29",
    "sku": "LAPT-0700",
    "slug": "asus-rog-zephyrus-g16-laptop-1",
    "name": "ASUS ROG Zephyrus G16 A100",
    "brand": "ASUS ROG",
    "description": "ASUS ROG Zephyrus G16 A100 — gaming and creator laptops.",
    "categorySlug": "laptop",
    "priceCents": 130520,
    "stockStatus": "low-stock",
    "specs": {
      "CPU": "Core i9",
      "GPU": "RTX 4060",
      "Display": "16\" 165 Hz",
      "RAM": "16 GB"
    },
    "imageUrl": "http://localhost:8080/images/laptop1.webp"
  },
  {
    "id": "30",
    "sku": "LAPT-0701",
    "slug": "razer-blade-16-laptop-2",
    "name": "Razer Blade 16 B101",
    "brand": "Razer",
    "description": "Razer Blade 16 B101 — gaming and creator laptops.",
    "categorySlug": "laptop",
    "priceCents": 131041,
    "stockStatus": "in-stock",
    "specs": {
      "CPU": "Ryzen 9",
      "GPU": "RTX 4070",
      "Display": "17.3\" 240 Hz",
      "RAM": "32 GB"
    },
    "imageUrl": "http://localhost:8080/images/laptop2.webp"
  },
  {
    "id": "31",
    "sku": "LAPT-0702",
    "slug": "lenovo-legion-legion-pro-7-laptop-3",
    "name": "Lenovo Legion Legion Pro 7 C102",
    "brand": "Lenovo Legion",
    "description": "Lenovo Legion Legion Pro 7 C102 — gaming and creator laptops.",
    "categorySlug": "laptop",
    "priceCents": 131562,
    "stockStatus": "in-stock",
    "specs": {
      "CPU": "Core i9",
      "GPU": "RTX 4080",
      "Display": "18\" 300 Hz",
      "RAM": "48 GB"
    },
    "imageUrl": "http://localhost:8080/images/laptop3.webp"
  },
  {
    "id": "32",
    "sku": "LAPT-0703",
    "slug": "alienware-m18-laptop-4",
    "name": "Alienware m18 D103",
    "brand": "Alienware",
    "description": "Alienware m18 D103 — gaming and creator laptops.",
    "categorySlug": "laptop",
    "priceCents": 132083,
    "stockStatus": "in-stock",
    "specs": {
      "CPU": "Ryzen 9",
      "GPU": "RTX 4090",
      "Display": "16\" 165 Hz",
      "RAM": "64 GB"
    },
    "imageUrl": "http://localhost:8080/images/laptop1.webp"
  },
  {
    "id": "33",
    "sku": "MEM-0800",
    "slug": "corsair-vengeance-memory-1",
    "name": "Corsair Vengeance A100",
    "brand": "Corsair",
    "description": "Corsair Vengeance A100 — ddr5 and ddr4 ram kits.",
    "categorySlug": "memory",
    "priceCents": 6520,
    "stockStatus": "in-stock",
    "specs": {
      "Capacity": "16 GB",
      "Type": "DDR4",
      "Speed": "5600 MT/s",
      "Latency": "CL30"
    },
    "imageUrl": "http://localhost:8080/images/memory1.png"
  },
  {
    "id": "34",
    "sku": "MEM-0801",
    "slug": "g-skill-trident-z5-memory-2",
    "name": "G.Skill Trident Z5 B101",
    "brand": "G.Skill",
    "description": "G.Skill Trident Z5 B101 — ddr5 and ddr4 ram kits.",
    "categorySlug": "memory",
    "priceCents": 7041,
    "stockStatus": "in-stock",
    "specs": {
      "Capacity": "32 GB",
      "Type": "DDR5",
      "Speed": "6000 MT/s",
      "Latency": "CL31"
    },
    "imageUrl": "http://localhost:8080/images/memory2.jpg"
  },
  {
    "id": "35",
    "sku": "MEM-0802",
    "slug": "kingston-fury-beast-memory-3",
    "name": "Kingston Fury Beast C102",
    "brand": "Kingston",
    "description": "Kingston Fury Beast C102 — ddr5 and ddr4 ram kits.",
    "categorySlug": "memory",
    "priceCents": 7562,
    "stockStatus": "in-stock",
    "specs": {
      "Capacity": "64 GB",
      "Type": "DDR5",
      "Speed": "6400 MT/s",
      "Latency": "CL32"
    },
    "imageUrl": "http://localhost:8080/images/memory3.png"
  },
  {
    "id": "36",
    "sku": "MEM-0803",
    "slug": "crucial-pro-oc-memory-4",
    "name": "Crucial Pro OC D103",
    "brand": "Crucial",
    "description": "Crucial Pro OC D103 — ddr5 and ddr4 ram kits.",
    "categorySlug": "memory",
    "priceCents": 8083,
    "stockStatus": "in-stock",
    "specs": {
      "Capacity": "96 GB",
      "Type": "DDR4",
      "Speed": "7200 MT/s",
      "Latency": "CL33"
    },
    "imageUrl": "http://localhost:8080/images/memory4.jpg"
  },
  {
    "id": "37",
    "sku": "MON-0900",
    "slug": "lg-ultragear-monitor-1",
    "name": "LG UltraGear A100",
    "brand": "LG",
    "description": "LG UltraGear A100 — high-refresh gaming displays.",
    "categorySlug": "monitor",
    "priceCents": 20520,
    "stockStatus": "in-stock",
    "specs": {
      "Size": "27\"",
      "Resolution": "1440p",
      "Refresh": "144 Hz",
      "Panel": "IPS"
    },
    "imageUrl": "http://localhost:8080/images/monitor1.webp"
  },
  {
    "id": "38",
    "sku": "MON-0901",
    "slug": "samsung-odyssey-oled-monitor-2",
    "name": "Samsung Odyssey OLED B101",
    "brand": "Samsung",
    "description": "Samsung Odyssey OLED B101 — high-refresh gaming displays.",
    "categorySlug": "monitor",
    "priceCents": 21041,
    "stockStatus": "in-stock",
    "specs": {
      "Size": "32\"",
      "Resolution": "4K",
      "Refresh": "165 Hz",
      "Panel": "OLED"
    },
    "imageUrl": "http://localhost:8080/images/monitor2.jpg"
  },
  {
    "id": "39",
    "sku": "MON-0902",
    "slug": "asus-rog-swift-pg-monitor-3",
    "name": "ASUS ROG Swift PG C102",
    "brand": "ASUS ROG",
    "description": "ASUS ROG Swift PG C102 — high-refresh gaming displays.",
    "categorySlug": "monitor",
    "priceCents": 21562,
    "stockStatus": "in-stock",
    "specs": {
      "Size": "34\"",
      "Resolution": "Ultrawide 1440p",
      "Refresh": "240 Hz",
      "Panel": "IPS"
    },
    "imageUrl": "http://localhost:8080/images/monitor1.webp"
  },
  {
    "id": "40",
    "sku": "MON-0903",
    "slug": "dell-alienware-aw-monitor-4",
    "name": "Dell Alienware AW D103",
    "brand": "Dell",
    "description": "Dell Alienware AW D103 — high-refresh gaming displays.",
    "categorySlug": "monitor",
    "priceCents": 22083,
    "stockStatus": "in-stock",
    "specs": {
      "Size": "49\"",
      "Resolution": "DQHD",
      "Refresh": "360 Hz",
      "Panel": "OLED"
    },
    "imageUrl": "http://localhost:8080/images/monitor2.jpg"
  },
  {
    "id": "41",
    "sku": "MOBO-1000",
    "slug": "asus-rog-maximus-z790-motherboard-1",
    "name": "ASUS ROG Maximus Z790 A100",
    "brand": "ASUS ROG",
    "description": "ASUS ROG Maximus Z790 A100 — boards for every platform.",
    "categorySlug": "motherboard",
    "priceCents": 15520,
    "stockStatus": "in-stock",
    "specs": {
      "Socket": "LGA1700",
      "Chipset": "Z790",
      "Memory Slots": "4× DDR5",
      "M.2 Slots": "3"
    },
    "imageUrl": "http://localhost:8080/images/motherboard1.webp"
  },
  {
    "id": "42",
    "sku": "MOBO-1001",
    "slug": "msi-meg-x670e-motherboard-2",
    "name": "MSI MEG X670E B101",
    "brand": "MSI",
    "description": "MSI MEG X670E B101 — boards for every platform.",
    "categorySlug": "motherboard",
    "priceCents": 16041,
    "stockStatus": "in-stock",
    "specs": {
      "Socket": "AM5",
      "Chipset": "X670E",
      "Memory Slots": "4× DDR5",
      "M.2 Slots": "4"
    },
    "imageUrl": "http://localhost:8080/images/motherboard2.webp"
  },
  {
    "id": "43",
    "sku": "MOBO-1002",
    "slug": "gigabyte-aorus-master-motherboard-3",
    "name": "Gigabyte AORUS Master C102",
    "brand": "Gigabyte",
    "description": "Gigabyte AORUS Master C102 — boards for every platform.",
    "categorySlug": "motherboard",
    "priceCents": 16562,
    "stockStatus": "in-stock",
    "specs": {
      "Socket": "LGA1700",
      "Chipset": "B650",
      "Memory Slots": "4× DDR5",
      "M.2 Slots": "5"
    },
    "imageUrl": "http://localhost:8080/images/motherboard3.webp"
  },
  {
    "id": "44",
    "sku": "MOBO-1003",
    "slug": "asrock-taichi-motherboard-4",
    "name": "ASRock Taichi D103",
    "brand": "ASRock",
    "description": "ASRock Taichi D103 — boards for every platform.",
    "categorySlug": "motherboard",
    "priceCents": 17083,
    "stockStatus": "out-of-stock",
    "specs": {
      "Socket": "AM5",
      "Chipset": "B760",
      "Memory Slots": "4× DDR5",
      "M.2 Slots": "3"
    },
    "imageUrl": "http://localhost:8080/images/motherboard4.webp"
  },
  {
    "id": "45",
    "sku": "MOUSE-1100",
    "slug": "logitech-g-g-pro-x-superlight-2-mouse-1",
    "name": "Logitech G G Pro X Superlight 2 A100",
    "brand": "Logitech G",
    "description": "Logitech G G Pro X Superlight 2 A100 — gaming mice and sensors.",
    "categorySlug": "mouse",
    "priceCents": 4520,
    "stockStatus": "in-stock",
    "specs": {
      "Sensor": "Optical 30K",
      "DPI": "18,000",
      "Weight": "55 g",
      "Connectivity": "Wired USB-C"
    },
    "imageUrl": "http://localhost:8080/images/mouse1.webp"
  },
  {
    "id": "46",
    "sku": "MOUSE-1101",
    "slug": "razer-viper-v3-pro-mouse-2",
    "name": "Razer Viper V3 Pro B101",
    "brand": "Razer",
    "description": "Razer Viper V3 Pro B101 — gaming mice and sensors.",
    "categorySlug": "mouse",
    "priceCents": 5041,
    "stockStatus": "in-stock",
    "specs": {
      "Sensor": "Optical 30K",
      "DPI": "25,600",
      "Weight": "58 g",
      "Connectivity": "2.4 GHz Wireless"
    },
    "imageUrl": "http://localhost:8080/images/mouse2.webp"
  },
  {
    "id": "47",
    "sku": "MOUSE-1102",
    "slug": "steelseries-aerox-5-mouse-3",
    "name": "SteelSeries Aerox 5 C102",
    "brand": "SteelSeries",
    "description": "SteelSeries Aerox 5 C102 — gaming mice and sensors.",
    "categorySlug": "mouse",
    "priceCents": 5562,
    "stockStatus": "out-of-stock",
    "specs": {
      "Sensor": "Optical 30K",
      "DPI": "30,000",
      "Weight": "61 g",
      "Connectivity": "Wired USB-C"
    },
    "imageUrl": "http://localhost:8080/images/mouse3.webp"
  },
  {
    "id": "48",
    "sku": "MOUSE-1103",
    "slug": "glorious-model-o-mouse-4",
    "name": "Glorious Model O D103",
    "brand": "Glorious",
    "description": "Glorious Model O D103 — gaming mice and sensors.",
    "categorySlug": "mouse",
    "priceCents": 6083,
    "stockStatus": "low-stock",
    "specs": {
      "Sensor": "Optical 30K",
      "DPI": "35,000",
      "Weight": "64 g",
      "Connectivity": "2.4 GHz Wireless"
    },
    "imageUrl": "http://localhost:8080/images/mouse1.webp"
  },
  {
    "id": "49",
    "sku": "PSU-1200",
    "slug": "corsair-rm1000x-powersupply-1",
    "name": "Corsair RM1000x A100",
    "brand": "Corsair",
    "description": "Corsair RM1000x A100 — efficient, quiet psus.",
    "categorySlug": "powersupply",
    "priceCents": 9520,
    "stockStatus": "in-stock",
    "specs": {
      "Wattage": "650 W",
      "Rating": "80+ Gold",
      "Modular": "Fully Modular",
      "Fan": "120 mm"
    },
    "imageUrl": "http://localhost:8080/images/powersupply1.webp"
  },
  {
    "id": "50",
    "sku": "PSU-1201",
    "slug": "seasonic-prime-tx-powersupply-2",
    "name": "Seasonic PRIME TX B101",
    "brand": "Seasonic",
    "description": "Seasonic PRIME TX B101 — efficient, quiet psus.",
    "categorySlug": "powersupply",
    "priceCents": 10041,
    "stockStatus": "out-of-stock",
    "specs": {
      "Wattage": "750 W",
      "Rating": "80+ Platinum",
      "Modular": "Fully Modular",
      "Fan": "135 mm FDB"
    },
    "imageUrl": "http://localhost:8080/images/powersupply2.webp"
  },
  {
    "id": "51",
    "sku": "PSU-1202",
    "slug": "be-quiet-dark-power-13-powersupply-3",
    "name": "be quiet! Dark Power 13 C102",
    "brand": "be quiet!",
    "description": "be quiet! Dark Power 13 C102 — efficient, quiet psus.",
    "categorySlug": "powersupply",
    "priceCents": 10562,
    "stockStatus": "low-stock",
    "specs": {
      "Wattage": "850 W",
      "Rating": "80+ Titanium",
      "Modular": "Fully Modular",
      "Fan": "120 mm"
    },
    "imageUrl": "http://localhost:8080/images/powersupply3.webp"
  },
  {
    "id": "52",
    "sku": "PSU-1203",
    "slug": "evga-supernova-powersupply-4",
    "name": "EVGA SuperNOVA D103",
    "brand": "EVGA",
    "description": "EVGA SuperNOVA D103 — efficient, quiet psus.",
    "categorySlug": "powersupply",
    "priceCents": 11083,
    "stockStatus": "in-stock",
    "specs": {
      "Wattage": "1000 W",
      "Rating": "80+ Gold",
      "Modular": "Fully Modular",
      "Fan": "135 mm FDB"
    },
    "imageUrl": "http://localhost:8080/images/powersupply1.webp"
  },
  {
    "id": "53",
    "sku": "STOR-1300",
    "slug": "samsung-990-pro-storage-1",
    "name": "Samsung 990 Pro A100",
    "brand": "Samsung",
    "description": "Samsung 990 Pro A100 — nvme ssds and drives.",
    "categorySlug": "storage",
    "priceCents": 9520,
    "stockStatus": "out-of-stock",
    "specs": {
      "Capacity": "1 TB",
      "Interface": "PCIe 4.0 ×4",
      "Seq Read": "7000 MB/s",
      "Seq Write": "6300 MB/s"
    },
    "imageUrl": "http://localhost:8080/images/memory1.png"
  },
  {
    "id": "54",
    "sku": "STOR-1301",
    "slug": "wd-black-sn850x-storage-2",
    "name": "WD Black SN850X B101",
    "brand": "WD",
    "description": "WD Black SN850X B101 — nvme ssds and drives.",
    "categorySlug": "storage",
    "priceCents": 10041,
    "stockStatus": "low-stock",
    "specs": {
      "Capacity": "2 TB",
      "Interface": "PCIe 4.0 ×4",
      "Seq Read": "7100 MB/s",
      "Seq Write": "6400 MB/s"
    },
    "imageUrl": "http://localhost:8080/images/memory2.jpg"
  },
  {
    "id": "55",
    "sku": "STOR-1302",
    "slug": "crucial-t700-storage-3",
    "name": "Crucial T700 C102",
    "brand": "Crucial",
    "description": "Crucial T700 C102 — nvme ssds and drives.",
    "categorySlug": "storage",
    "priceCents": 10562,
    "stockStatus": "in-stock",
    "specs": {
      "Capacity": "4 TB",
      "Interface": "PCIe 4.0 ×4",
      "Seq Read": "7200 MB/s",
      "Seq Write": "6500 MB/s"
    },
    "imageUrl": "http://localhost:8080/images/memory3.png"
  },
  {
    "id": "56",
    "sku": "STOR-1303",
    "slug": "seagate-firecuda-530-storage-4",
    "name": "Seagate FireCuda 530 D103",
    "brand": "Seagate",
    "description": "Seagate FireCuda 530 D103 — nvme ssds and drives.",
    "categorySlug": "storage",
    "priceCents": 11083,
    "stockStatus": "in-stock",
    "specs": {
      "Capacity": "1 TB",
      "Interface": "PCIe 4.0 ×4",
      "Seq Read": "7300 MB/s",
      "Seq Write": "6600 MB/s"
    },
    "imageUrl": "http://localhost:8080/images/memory4.jpg"
  }
];
